---
title: "compare_marginal_fitting"
output: html_document
---

```{r}
library(ggplot2)
library(tidyverse)
library(goftest)
library(purrr)
source("dev_utils.R")

margin_comparison_file <- "output/margin_estimation_comparison.rds"
margin_comparisons <- readRDS(margin_comparison_file)
```
```{r}
# filter na 
margin_comparisons$sigma <- margin_comparisons$settings |> stringr::str_split_i(":", 2) |> as.numeric()

```

```{r}
# add 
margin_comparisons <- margin_comparisons |>  mutate(setting = case_when(
    settings == "MLE" ~ "'MLE'",
    settings == "beta_prior" ~ "'PE prior'",
    TRUE ~ paste("sigma[prior]", "==", sigma)
  ))
# Get unique sigma values and sort them
sigma_values <- unique(margin_comparisons$sigma[margin_comparisons$settings != "MLE" & margin_comparisons$settings != "beta_prior"])
sigma_values <- sort(sigma_values)

# Create the ordered levels
sigma_expressions <- sapply(sigma_values, function(x)  paste("sigma[prior]", "==", x))
desired_order <- c("'PE prior'", sigma_expressions, "'MLE'")

# Convert to factor with desired order
margin_comparisons$setting <- factor(margin_comparisons$setting, levels = desired_order)

margin_comparisons$prediction_method <- interaction(margin_comparisons$setting, margin_comparisons$decoupler,  sep = ":")
```

```{r}
split_by_setting <- margin_comparisons |> split(margin_comparisons$prediction_method) 
margin_settings_names <- split_by_setting |> map_chr(\(df) df$prediction_method |> unique() |> as.character())

margin_comparisons_CDF <- margin_comparisons |> filter(str_ends(prediction_method, "CDF"))
margin_comparisons_relative <- margin_comparisons |> filter(str_detect(prediction_method, "Rel."))
margin_comparisons_relative <- margin_comparisons_relative |> dplyr::mutate(k=as.numeric(stringr::str_split_i(decoupler, "=", 2)))
k_values <- margin_comparisons_relative$k |> unique()
```

```{r}
nr_na <- margin_comparisons |> group_by(decoupler, setting) |> summarise(nr_na = sum(is.na(likelihood)), 
  nr_total = n()) |> ungroup() |> arrange(desc(nr_na))
nr_na |> arrange(desc(nr_na))
# save  nr_na to csv
write_csv(nr_na, "output/margin_estimation_na_counts.csv")
nr_na
```
```{r}
margin_comparisons <- margin_comparisons |> filter(is.finite(likelihood))
```


```{r}
# calculate linear error
margin_comparisons$linear_E <- abs(margin_comparisons$realization - margin_comparisons$median)
margin_comparisons$squared_E <- (margin_comparisons$realization - margin_comparisons$mean)^2
# calculate the mean errors
margin_error_table <- margin_comparisons |> group_by(decoupler, setting) |> 
  summarise(
    MAE_median = mean(linear_E, na.rm=TRUE),
    MedAE_median = median(linear_E, na.rm=TRUE),
    RMSE_mean = sqrt(mean(squared_E, na.rm=TRUE)),
    .groups = "drop"
  )
margin_error_table |> arrange(MAE_median) 
margin_error_table |> arrange(RMSE_mean) 
# save table
```

```{r}
p_absolute_median_error <- margin_comparisons |> ggplot(aes(x=prediction_method, y=linear_E)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(
    title = "likelihood of Marginal Estimations",
    y = "Absolute median-error",
    x = "Method"
  ) +
  scale_x_discrete(labels=label_parsed)
ggsave("output/marginal_comparisons_absolute_median_error.pdf", p_absolute_median_error, width=10, height=7)
p_absolute_median_error
```
```{r}
margin_comparisons |> ggplot(aes(x=prediction_method, y=squared_E)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(
    title = "likelihood of Marginal Estimations",
    x = "prediction_method of Settings and Decoupler",
    y = "Squared Absolute Mean-Error"
  )
```




```{r}
# function to make histogram_plot 
make_histogram <- function(df) {
  df |> ggplot(aes(x=cdf_value)) +
  geom_histogram(boundary=0, binwidth=0.05) +
  facet_wrap(vars(setting), labeller = label_parsed)
}

p_cdf_histogram <- margin_comparisons_CDF |> make_histogram() 
ggsave("output/marginal_comparisons_CDF_histogram.pdf", p_cdf_histogram, width=10, height=7)
p_cdf_histogram
```

```{r}
p_k_plots <- purrr::map(k_values, function(k_val) {
  margin_comparisons_relative |> filter(k==k_val) |> make_histogram() 
})
# save plots
purrr::walk(seq_along(p_k_plots), function(i) {
  ggsave(paste0("output/marginal_comparisons_relative_k_", k_values[i], "_histogram.pdf"), p_k_plots[[i]], width=10, height=7)
})
p_k_plots[[3]]
```

```{r}
plot_emperical_CDF_compaison <- function(df) {
  ggplot(df, aes(x=cdf_value)) +
    stat_ecdf() +
    geom_abline(slope=1,intercept=0,linetype="dashed") + 
    facet_wrap(vars(setting), labeller = label_parsed)
}

plot_emperical_CDF_compaison_sigmoid <- function(df) {
  ggplot(df, aes(x=cdf_value)) +
    stat_ecdf() +
    geom_abline(slope=1,intercept=0,linetype="dashed") + 
    facet_grid(vars(decoupler), vars(k))
}

ecdf_cdf_plot <- margin_comparisons_CDF |> plot_emperical_CDF_compaison()
ggsave("output/marginal_comparisons_CDF.pdf", ecdf_cdf_plot, width=10, height=7)
ecdf_relative_plots <- purrr::map(k_values, \(k_val) margin_comparisons_relative |> filter(k==k_val) |> plot_emperical_CDF_compaison())

purrr::walk(seq_along(ecdf_relative_plots), function(i) {
  ggsave(paste0("output/marginal_comparisons_relative_k_", k_values[i], ".pdf"), ecdf_relative_plots[[i]], width=10, height=7)
})
ecdf_cdf_plot
```
```{r}
ecdf_relative_plots[[4]]
```


```{r}
# Compute distance to uniform distribution
# for each setting



marginal_est_metrics <- split_by_setting |>   purrr::map(\(df) {
    metrics <- calculate_uniformity_metrics(df$cdf_value)
    tibble::tibble_row(
      setting = unique(df$setting),
      prediction_method = unique(df$prediction_method),
      decoupler = unique(df$decoupler),
      settings = unique(df$settings),
      !!!metrics
    )
  })  |> purrr::list_rbind()

# prediction_method columns with margin_error_table
margin_point_estimate_table <- marginal_est_metrics |> 
  left_join(margin_error_table, by = c("setting", "decoupler")) 

margin_point_estimate_table |> select(setting, decoupler, MAE_median, MedAE_median, RMSE_mean, L1, L2) |> 
  arrange(L1) |> 
  write_csv("output/marginal_est_metrics.csv")

# filter to only display CDF and k=0.05 relative decoupler
margin_point_estimate_table |> filter(str_ends(prediction_method, "CDF") | str_detect(prediction_method, "0.05")) |> 
  select(setting, decoupler, MAE_median, MedAE_median, RMSE_mean, L1, L2) |>
  arrange(L1) |> 
  write_csv("output/marginal_est_metrics_CDF_Rel_k_0.05.csv")

# get the 5 rows with lowest cvm_statistic
top_5_marginal_methods <- marginal_est_metrics |> arrange(L1) |> head(5)
# save to csv
write_csv(top_5_marginal_methods, "output/top_5_marginal_methods.csv")
top_5_marginal_methods
# cvm_tests |> purrr::map(\(test) { # This is not too informative because I have so many samples it gives really low p values.
#   test$p.value
# })
```

```{r}
# Get the prediction methods with cdf
CDF_table_best_performers <- marginal_est_metrics |> filter(str_ends(prediction_method, "CDF")) |> arrange(L1) 
# save to csv
write_csv(CDF_table_best_performers, "output/CDF_table_best_performers.csv")
CDF_table_best_performers
```
```{r}
# get best performers for relative decouplers
relative_table_best_performers <- marginal_est_metrics |> filter(str_detect(prediction_method, "Rel.")) |> arrange(L1)
```



```{r}



#margin_comparisons |> filter(prediction_method=="betaH:1.s((q-m)/(|m|+e))") 
make_likelihood_boxplots <- function(df) {
  df |>  filter(likelihood<10)  |> ggplot2::ggplot(aes(x=prediction_method, y=likelihood)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
}

margin_comparisons_CDF |> make_likelihood_boxplots()
margin_comparisons |> make_likelihood_boxplots()
```
```{r}
margin_comparisons |> filter(is.finite(likelihood)) |> group_by(prediction_method) |> summarise(
  mean_likelihoods=mean(likelihood),
  median_likelihoods=median(likelihood),
  sd_likelihoods=sd(likelihood),
  min_likelihoods=min(likelihood),
  max_likelihoods=max(likelihood),
  q_5 = quantile(likelihood, 0.05)
) |> arrange(q_5)
```
